### ISSUE TITLE
Incorrect source map when "to" option passed

### ISSUE THREAD

**Issue by htanjo** [postcss/gulp-postcss#64] opened 2015-12-14 03:40 UTC
I'm using gulp-sass, gulp-postcss and gulp-sourcemaps in [my project](https://github.com/htanjo/gulp-boilerplate). 
When I set `to` option in the `postcss()`, the source map content is incorrect.

```js
gulp.src('app/styles/*.scss')
  .pipe($.sourcemaps.init({loadMaps: true}))
  .pipe($.sass().on('error', $.sass.logError))
  .pipe($.postcss(processors, {to: '.tmp/styles/main.css'}))
  .pipe($.sourcemaps.write('.'))
  .pipe(gulp.dest('.tmp/styles'))
```

![postcss-sourcemaps](https://cloud.githubusercontent.com/assets/774048/11772112/7044124e-a25c-11e5-9cc6-ba09c4438a7d.png)

Without `to` option, I could get proper source map, but some postcss plugins need this option.
Am I overlooking something, or is this bug?

I created simple gulp tasks to reproduce this issue. I hope this helps.
https://github.com/htanjo/postcss-sourcemaps-test

**Comment by TrySound** [comment] 2015-12-14 10:16
@htanjo Which plugins need this option?

**Comment by htanjo** [comment] 2015-12-15 00:47
In my project, [postcss-copy-assets](https://github.com/shutterstock/postcss-copy-assets) requires it.
And I tried [postcss-copy](https://github.com/geut/postcss-copy) previously, it also depends on `to` option.

**Comment by w0rm** [comment] 2015-12-15 23:18
@htanjo sorry for the delay, I'm extremely busy this week, will be able to check it over the Weekend.

**Comment by htanjo** [comment] 2015-12-16 00:48
@w0rm That's ok! Thanks.

**Comment by w0rm** [comment] 2015-12-19 14:36
@htanjo I sent you a temporary fix that should work.

Sourcemaps are really complicated in gulp. The source map from the previous operation has to be combined with the sourcemap from the next operation. This only works when `file` from the previous map matches element from `sources` of the current map.

This is what was happening when the `to='dist/main.css'` option was set:

`previousMap = {sources: [ 'main.scss' ], file: 'main.css'}`
`currentMap = {sources: [ '../src/main.css' ], file: 'main.css'}`

Because `main.css` and `../src/main.css` do not match, only the `currentMap` was output.

**Comment by w0rm** [comment] 2015-12-19 14:42
It seems that I can only properly fix this issue after this is implemented in postcss: https://github.com/postcss/postcss/issues/240

**Comment by htanjo** [comment] 2015-12-21 04:13
@w0rm I see...! I understood the situation.
Your workaround is very helpful and I'll use it at the moment.
Thanks!

**Comment by alvint** [comment] 2015-12-28 18:36
I get the same issue regardless of the `to` option. In fact, even if I run postcss with an empty processor list and no options I have this problem. The issue is also affecting plugins which rely on postcss, such as gulp-autoprefixer.

**Comment by w0rm** [comment] 2015-12-28 20:57
@alvint hi, if it happens regardless of the `to` option then it's not related to this issue. Please open a separate issue and add a link to a minimal project that reproduces it. This way I will be able to help you.

Sometimes gulp-postcss is not even an issue. A previous gulp plugin may generate a wrong source map that cannot be merged, so I really need to see the code to figure out what went wrong!

**Comment by evilebottnawi** [comment] 2016-02-11 17:47
Some issue, I try to understand in detail what the problem is

**Comment by timkraut** [comment] 2016-09-13 10:29
Any updates on that?

**Comment by w0rm** [comment] 2016-09-13 10:53
@timkraut nope and https://github.com/postcss/postcss/issues/240 wasn't implemented.

**Comment by w0rm** [comment] 2016-10-23 15:01
Closing because https://github.com/postcss/postcss/issues/240 is closed.

**Closed by w0rm** 2016-10-23 15:01 UTC
