### ISSUE TITLE
Cannot parse .pcss file

### ISSUE THREAD

**Issue by sevenupcan** [postcss/gulp-postcss#75] opened 2016-03-11 14:03 UTC
In my project both the preprocessed file and processed file live in the same location so I need to give each of them a different file extension. However gulp will not recognise `.pcss` or `.postcss`.

For example I have the following:
```
gulp.task('css', function () {
    var postcss    = require('gulp-postcss');
    var sourcemaps = require('gulp-sourcemaps');
    var rename = require('gulp-rename');

    return gulp.src('src/**/*.pcss', {base: './'})
        .pipe( sourcemaps.init() )
        .pipe( postcss([ require('autoprefixer'), require('precss') ]) )
        .pipe( sourcemaps.write('.') )
        .pipe( rename({extname: '.css'}) )
        .pipe( gulp.dest('./') );
});
```
Any idea why this could be?

**Comment by TrySound** [comment] 2016-03-11 14:58
@sevenupcan Do you mean there are not output files?

**Comment by sevenupcan** [comment] 2016-03-11 16:49
@TrySound hi, yes sorry. When I just the example task above no files are outputted.

**Comment by TrySound** [comment] 2016-03-11 17:43
@sevenupcan Then the problem is not in postcss or another plugin. Something wrong with source/dest paths or your file structure.

**Comment by sevenupcan** [comment] 2016-03-11 20:33
It's not got anything to do with the source or destination folders or file structure. I've tried it with a much simpler task and the same problem still happens. Perhaps gulp.src only accepts certain file names?

**Comment by TrySound** [comment] 2016-03-11 20:47
Did you try without sourcemaps and postcss?

**Comment by sevenupcan** [comment] 2016-03-11 20:49
For example this works:

```
gulp.task('css', function () {
    var rename = require('gulp-rename');

    return gulp.src('test/*.scss')
        .pipe( rename({extname: '.css'}) )
        .pipe( gulp.dest('dest/') );
});
```

This doesn't:
```
gulp.task('css', function () {
    var rename = require('gulp-rename');

    return gulp.src('test/*.pcss')
        .pipe( rename({extname: '.css'}) )
        .pipe( gulp.dest('dest/') );
});
```

**Comment by TrySound** [comment] 2016-03-11 21:17
@sevenupcan Are you sure your files has `.pcss` extensions? Did you rename them manually to scss?

**Comment by sevenupcan** [comment] 2016-03-11 21:52
Yes, I have triple checked!!! Try it yourself.

**Comment by w0rm** [comment] 2016-03-12 10:07
@sevenupcan this works for me:

![screen shot 2016-03-12 at 11 05 52](https://cloud.githubusercontent.com/assets/43472/13722339/74f9b95c-e842-11e5-8fc3-6a85bece45af.png)

I'm closing the issue because this doesn't have anything to do with gulp-postcss, but feel free to continue discussion.

**Closed by w0rm** 2016-03-12 10:07 UTC

**Comment by sevenupcan** [comment] 2016-03-12 10:55
Thanks. I tested everything from scratch and it does work. Sorry for wasting you time :(.

When I look at finder and my text editor I notice Finder is lying to me!!!

<img width="504" alt="screenshot at mar 12 10-52-33" src="https://cloud.githubusercontent.com/assets/5551/13722529/af57043a-e840-11e5-9381-2d4aa059f27d.png">

Any ideas why it's not showing the correct file extention?

**Comment by w0rm** [comment] 2016-03-12 11:02
@sevenupcan there is an option in Finder preferences "Show all filename extensions"
