### ISSUE TITLE
Fails silently with missing file and postcss-import

### ISSUE THREAD

**Issue by timkelty** [postcss/gulp-postcss#32] opened 2015-04-15 15:43 UTC
It should throw an error: https://github.com/postcss/postcss-import/issues/35#issuecomment-93453325

But when using `gulp-postcss` w/ `postcss-import` and you try to import a missing file, the gulp task never finishes and postcss processing seems to abort.

**Comment by w0rm** [comment] 2015-04-15 20:22
Given this gulpfile

```js
var gulp = require('gulp')
var postcss = require('gulp-postcss')
var postcssImport = require('postcss-import')

gulp.task('default', function () {

  return gulp
    .src('src/style.css')
    .pipe(postcss([postcssImport()]))
    .on('error', function (error) {
      console.log(error)
    })
    .pipe(gulp.dest('dest'))

})
```

and this css file `src/style.css`:

````css
@import "./missing.css";
```

I get the following output in the console:

```
{ [Error: Error: /Users/w0rm/Work/postcss-test/src/style.css:1:1: Failed to find './missing.css' from /Users/w0rm/Work/postcss-test
    in [ 
        /Users/w0rm/Work/postcss-test/src
    ]]
  message: 'Error: /Users/w0rm/Work/postcss-test/src/style.css:1:1: Failed to find \'./missing.css\' from /Users/w0rm/Work/postcss-test\n    in [ \n        /Users/w0rm/Work/postcss-test/src\n    ]',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss',
  __safety: { toString: [Function] } }
```

**Comment by w0rm** [comment] 2015-04-16 18:50
@timkelty got no further input from your side, may I close this?

**Comment by timkelty** [comment] 2015-04-16 18:51
I'll test right now and see what's going on with my environment.

**Comment by olegstepura** [comment] 2015-04-28 12:05
Gulp-postcss (not sure, maybe postcss itself) seem to always fail silently. Any error with missing paths in some of the plugins causes it silently fail. It should print the error, this hardens debugging very much.

Issues noticed with `cssgrace` (when url points to missing file), `postcss-assets` with same problem of resolving paths.

**Comment by olegstepura** [comment] 2015-04-28 12:12
This is how it looks like:
```bash
web@web ~/gulp $ npm install gulp-postcss
gulp-postcss@5.1.3 node_modules/gulp-postcss
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.1.1, chalk@1.0.0, lodash.template@3.5.0, dateformat@1.0.11, multipipe@0.1.2)
web@web ~/gulp $ gulp build:css:next
[14:06:49] Using gulpfile ~/gulp/host/gulpfile.js
[14:06:49] Starting 'build:css:next'...
web@web ~/gulp $
```

**Comment by timkelty** [comment] 2015-04-28 12:16
Sticking [gulp-plumber](https://github.com/floatdrop/gulp-plumber) in the pipe right before postcss takes care of everything for me. @olegstepura I would give that a try if you haven't yet.

**Comment by olegstepura** [comment] 2015-04-28 12:25
It helps. Thanks!

**Comment by w0rm** [comment] 2015-04-28 19:25
gulp-postcss has [a test for correct stream error](https://github.com/postcss/gulp-postcss/blob/master/test.js#L38) that you can listen to and log to console.

It also [tests that in case of `cssSyntaxError`](https://github.com/postcss/gulp-postcss/blob/master/test.js#L197) it should emit a pretty error from postCSS instead of regular js stack trace.

According to [gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) an error should not be thrown, but it should be emitted.

**Comment by olegstepura** [comment] 2015-04-29 07:14
Well, stack trace is helpful when you don't know who did thrown an exception. In case of postcss plugins exceptions are no longer thrown by some gulp plugins, it's thrown by postcss plugins that know nothing about gulp.

**Comment by w0rm** [comment] 2015-04-29 08:59
@olegstepura of course stack trace is helpful, and it is there for non-cssSyntaxErrors, so feel free to subscribe to the stream error event and use your preferred method of displaying the errors. Tests should give you a hint of how to capture stream errors, or use gulp-plumber with gulp-postcss.

**Comment by olegstepura** [comment] 2015-04-29 09:09
I'm very exceited of the project `postcss` itself. but silent fails almost made stop trying. Also it seems some postcss plugins are still bad quality, plugin order matters, and so on... but thanks to @timkelty for pointing to `gulp-plumber`, I was thinking plumber was designed for other reasons.

This is an offtop, but don't you know if it is possible to tell plumber to print stack?

**Comment by olegstepura** [comment] 2015-04-29 09:18
Ok, seems the best way is to setup custom error logging function

**Comment by w0rm** [comment] 2015-04-29 09:24
@olegstepura feel free to open pull request to improve the quality of certain postcss plugins. This repository is only related to gulp plugin.

**Comment by simonsmith** [comment] 2015-05-05 10:55
Hoping this is the right place to ask, but what is the best way to surface warnings from postcss plugins now?

For example postcss-bem-linter uses the [warning class](https://github.com/postcss/postcss/blob/master/docs/api.md#warning-class) as seen [here](https://github.com/necolas/postcss-bem-linter/blob/master/lib/validate-selectors.js#L35). But I don't think this triggers an error in a stream?

Have tried using [postcss-log-warning](https://github.com/davidtheclark/postcss-log-warnings) with `throwError` set to `true` but still doesn't seem to throw an error.

Any thoughts?

**Comment by w0rm** [comment] 2015-05-05 11:20
@simonsmith  I think that warnings should behave differently from the errors, as far as I understand, according to guidelines they should be output in the console rather than emitted as errors. 

//cc @ai

**Comment by VinSpee** [comment] 2015-05-20 18:23
I'm also facing this issue, but plumber doesn't seem to be helping:

### given:
```js
gulp.task('styles:toolkit', function () {
  var sourcemaps = require('gulp-sourcemaps');
  var postcss = require('gulp-postcss');
  //var bem_linter = require('postcss-bem-linter');
  var calc = require('postcss-calc');
  var colorFunction = require('postcss-color-function');
  var customMedia = require('postcss-custom-media');
  var customProperties = require('postcss-custom-properties');
  var fontVariant = require('postcss-font-variant');
  var lost = require('lost');
  var inline = require('postcss-import');
  var nested = require('postcss-nested');
  var simpleVars = require('postcss-simple-vars');
  var plumber = require('gulp-plumber');
  var processors = [
    //bem_linter(),
    nested,
    inline(),
    customProperties(),
    calc(),
    simpleVars(),
    customMedia(),
    lost(),
    colorFunction(),
    fontVariant()
  ];
  return gulp.src(config.src.styles.toolkit)
    .pipe(sourcemaps.init())
    .pipe(plumber())
    .pipe(postcss(processors))
    .pipe(sourcemaps.write())
    .pipe(prefix())
    .pipe(gulpif(!config.dev, csso()))
    .pipe(gulp.dest(config.dest + '/assets/toolkit/styles'))
    .pipe(gulpif(config.dev, reload({stream:true})))
});
```

### running:
```bash
gulp styles:toolkit --dev
```

### resulting:
```bash
[14:21:19] Using gulpfile ~/projects/LevelEleven/ui-kit/gulpfile.js
[14:21:19] Starting 'styles:toolkit'...
```

**Comment by VinSpee** [comment] 2015-05-20 18:41
I also tried using postcss-log-warnings, now I get this:

```bash
gulp styles:toolkit
[14:41:10] Using gulpfile ~/projects/LevelEleven/ui-kit/gulpfile.js
[14:41:10] Starting 'styles:toolkit'...

** postcss-log-warnings: warnings were found **
```

but that's it.

**Comment by VinSpee** [comment] 2015-05-20 18:59
in addition, postcss-import IS finding these files:

```bash
$>  gulp styles:toolkit
[14:58:26] Using gulpfile ~/projects/LevelEleven/ui-kit/gulpfile.js
[14:58:26] Starting 'styles:toolkit'...
[ '/Users/vince/projects/LevelEleven/ui-kit/src/assets/toolkit/styles/toolkit.css',
  '/Users/vince/projects/LevelEleven/ui-kit/node_modules/suitcss-components-grid/index.css',
  '/Users/vince/projects/LevelEleven/ui-kit/node_modules/suitcss-components-grid/lib/grid.css',
  '/Users/vince/projects/LevelEleven/ui-kit/src/assets/toolkit/styles/dude.css' ]

** postcss-log-warnings: warnings were found **
```

**Comment by w0rm** [comment] 2015-05-20 20:16
@VinSpee sorry, I'm super busy and will only be able to look into this on the weekend.

**Comment by VinSpee** [comment] 2015-05-20 22:43
No problem! I appreciate you even looking at all. On a second glance, I think the issue may be in gulp-sourcemaps or maybe even gulp-autoprefixer because if I remove them, the build works. I'll close for now.

**Comment by davidtheclark** [comment] 2015-05-24 02:56
@VinSpee that issue is about postcss-log-warnings I believe, not gulp-postcss. See: https://github.com/davidtheclark/postcss-log-warnings/issues/6 --- working on figuring it out.

**Comment by w0rm** [comment] 2015-05-25 09:53
@davidtheclark   It seems something is indeed wrong in exception handling, problem explained in this gist: https://gist.github.com/w0rm/36ff0b4399a414384690

By default, if there is an unhandled error in the stream, gulp will terminate and output the error in the console, but this is not happening with gulp-postcss.

**Comment by w0rm** [comment] 2015-05-25 10:08
My guess is that it has something to do with promises, because an exception that is emitted from the transform function body is output in console, but the one from the postcss promise is not.

```javascript
    postcss(processors)
      .process(file.contents, opts)
      .then(handleResult, handleError) // this error is not in console

    handleError(new Error('this error will be output'))
```

**Closed** 2015-05-25 11:18 UTC
