### ISSUE TITLE
Cannot make sourcemaps work

### ISSUE THREAD

**Issue by sqal** [postcss/gulp-postcss#40] opened 2015-05-21 12:28 UTC
Hi everyone. I am fighting to get sourcemaps working with gulp-postcss plugin but I've run out of ideas, and don't know how to fix it. My sass task looks like this:

```
gulp.task('sass:dev', function() {
    gulp.src('app/styles/**/*.scss)
        .pipe($.sourcemaps.init())
        .pipe($.sass(config.sass).on('error', $.sass.logError))
        .pipe($.postcss([
            autoprefixer({
                browsers: ['last 2 versions']
            })
        ]))
        .pipe($.sourcemaps.write('.'))
        .pipe(gulp.dest('.tmp/assets/styles'))
        .pipe(reload({ stream: true }));
});
```
Above config generates app.css.map file in destination directory as it should but sourcemaps does not works in browser. Here you can see that source map file (broken): https://gist.github.com/sqal/f894149870da902707f8 However If i remove postcss from my task, everything works as it should: https://gist.github.com/sqal/d3328b6c283ddbfee88f
Is there some bug in postcss or am I missing something here? Any hints on why it is not working for me would be greatly appreciated :) Thanks.

// Forgot to mention. I am using gulp-postcss 5.1.6, gulp-sourcemaps 1.5.2 and autoprefixer-core 5.1.11

**Comment by w0rm** [comment] 2015-05-21 14:17
@sqal which version of gulp-sass do you use?

**Comment by sqal** [comment] 2015-05-21 14:44
@w0rm 2.0.1. But is sass version relevant here? Sourcemaps only does not work with postcss in the task, as I said before.

**Comment by w0rm** [comment] 2015-05-21 15:39
@sqal it may be, if the relative file name doesn't match the one specified in the sourcemap that is coming from the sass, then sourcemaps won't be combined.

**Comment by sqal** [comment] 2015-05-21 15:53
Hmm OK. But i also tested it with only one scss file, outcome was the same - postcss breaks sorucemaps :(

**Comment by w0rm** [comment] 2015-05-21 16:00
Probably this is connected with https://github.com/dlmanning/gulp-sass/issues/106

**Comment by w0rm** [comment] 2015-05-25 20:31
@sqal can you create a minimal project that reproduces this issue?

**Comment by ai** [comment] 2015-05-25 20:32
Maybe this issuw is relevant to https://github.com/postcss/autoprefixer/issues/453

**Comment by w0rm** [comment] 2015-05-25 20:41
@ai my idea is to check that `file.relative` and `file.sourceMap.file` are the same after `gulp-sass`, otherwise source maps won't be properly combined by `vinyl-sourcemaps-apply`. 

Perhaps a complex glob pattern 'app/styles/**/*.scss' sets a different `file.base`, but `gulp-sass` doesn't take this into account when generating source map.

**Comment by sqal** [comment] 2015-05-26 07:39
@w0rm here you go: https://github.com/sqal/gulp-postcss-issue-40

**Comment by w0rm** [comment] 2015-05-26 08:40
Awesome, thanks, I'll look into it tonight

**Comment by w0rm** [comment] 2015-05-26 18:19
@sqal works perfectly fine for me https://yadi.sk/i/GsfUZ1OJgtKDt

**Comment by sqal** [comment] 2015-05-26 19:04
@w0rm That's weird. This is what it looks like to me:

![](http://i.imgur.com/ET9wrDS.png)

Why I don't have path to .scss file but .css? however i can still edit .scss file in sources panel (chrome), doesn't work in Firefox at all. I think this is not working correctly properly, right?

**Comment by w0rm** [comment] 2015-05-26 19:11
@sqal maybe it is a limitation of Firefox or has something to do with how browserSync does its live updates. The source map is generated properly.

**Comment by w0rm** [comment] 2015-05-26 19:14
Closing this, because live updates and browser edit features are not related to gulp-postcss, and the correct sourcemap file is generated.

**Comment by sqal** [comment] 2015-05-26 19:19
But this is is what it looks like in FF when gulp-postcss is on http://prntscr.com/79perd (can't edit scss), and this is when is off (can edit)  http://prntscr.com/79pgcq am i wrong or not? because to me looks like something doesn't work correctly after all.

**Comment by w0rm** [comment] 2015-05-26 19:21
@sqal cannot see your screenshots.

**Comment by sqal** [comment] 2015-05-26 19:25
@w0rm Sorry..

with gulp-postcss - https://www.dropbox.com/s/0tkv2ow9clfr6zm/LRR32yD.png
without - https://www.dropbox.com/s/drpadlxvxsdl4xm/Zs4Yfy0.png

**Comment by w0rm** [comment] 2015-05-26 19:37
@sqal since its working in Chrome, might be a Firefox issue.

I downloaded recent Firefox, tried to reproduce, and couldn't. Screencast: https://yadi.sk/i/5D9I3FxtgtQWs

**Comment by sqal** [comment] 2015-05-26 19:41
@w0rm I have the latest version of Firefox. Maybe this is Windows related issue? Someone with Windows 7 can confirm this issue?

**Comment by w0rm** [comment] 2015-05-26 19:47
@sqal sorry I can't help you with this. 

If you want to verify source maps, remove browserSync, generate style.css and style.css.map, link to the css from a static html file, then open html file in the browser.

**Comment by sqal** [comment] 2015-05-26 19:53
@w0rm browserSync has nothing to do with that, gulp-postcss still seems to be problem, but all right, I give up on this.Thank you for your time anyway :)

**Comment by w0rm** [comment] 2015-05-26 19:55
If you have just three files, test.html style.css and style.css.map, then this might be reduced test case for the Firefox.

**Comment by w0rm** [comment] 2015-05-26 19:56
Ironically saying, source-map package is owned by mozilla.

**Comment by w0rm** [comment] 2015-05-26 22:21
@sqal I might give it a try tomorrow. Will try to download windows7 from modern.ie.

**Comment by w0rm** [comment] 2015-05-27 18:09
@sqal I can see app.scss in the recent Firefox for Windows 7. 

![screen shot 2015-05-27 at 20 06 58](https://cloud.githubusercontent.com/assets/43472/7843757/0ffb0bfc-04ac-11e5-9cac-9906c049ba14.png)

**Closed by w0rm** 2015-05-27 18:09 UTC
